name: Run test
on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install coverage pytest

      - name: Run tests and generate coverage report
        run: |
          coverage run -m pytest
          coverage report -m > coverage.txt

      - name: Update README with coverage badge
        run: |
          pip install coverage-badge
          coverage-badge -f -o coverage.svg
          sed -i 's|!\[Coverage\](coverage.svg)|![Coverage](./coverage.svg)|g' README.md
